name: build alpine-emu-dev

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - alpine/**

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  push:
    name: "alpine:${{ matrix.oses }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        oses:
          - nodejs18
          - nodejs20
          - wine
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v6
        with:
          context: ./alpine/${{ matrix.oses }}
          file: ./alpine/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/goover/alpine:${{ matrix.oses }}
